### PR TITLE
Version 0.9.0

### PR DESCRIPTION
**Pull request by kevinbeaty**
Will publish to npm and tag when you merge.

### CODE REVIEW

**Comment by tgriesser** [comment]
Are we checking in `/lib` on releases?

**Comment by tgriesser** [comment]
Oh, or you said just NPM, that'd be fine with me

**Comment by tgriesser** [comment]
:+1:

**Comment by kevinbeaty** [comment]
Published and tagged 0.9.0

**Comment by tgriesser** [comment]
Nice - might need to `git push -t`

**Comment by kevinbeaty** [comment]
Pushed tags to `transduce:master`

I think I previously pushed tags to kevinbeaty/transduce accidentally...

**Pull request merged**
